// Generated by GraphWalker (http://www.graphwalker.org) 
package org.graphwalker.example.models;

import org.graphwalker.core.annotations.Model;

@Model(file = "org/graphwalker/example/models/ShoppingCart.graphml", type = "graphml")
public interface ShoppingCart {

    void e_ShoppingCart();

    void v_BrowserStarted();

    void Start();

    void v_OtherBoughtBooks();

    void e_EnterBaseURL();

    void e_AddBookToCart();

    void e_SearchBook();

    void e_StartBrowser();

    void v_BookInformation();

    void v_ShoppingCart();

    void v_SearchResult();

    void v_BaseURL();

    void e_ClickBook();
}
